### ISSUE TITLE
Clicking the X button on the login form sometimes sends it back to the splash screen

### ISSUE THREAD

**Issue by BlueDragonFire** [Tech-Army-Shared/TechArmy#4]
There is a persistent bug where sometimes, randomly, when the X button in the login form is clicked then instead of closing, the splash screen opens again and takes you straight back to the login screen. When pressing the X button for the _second_ time then it will actually close.

This bug is sporadic and doesn't always occur. Most times it seems to occur when starting up a fresh build for the first time.

@MemelaPido just wanted to bring your attention to this

**Comment by MemelaPido** [comment]
Ey brvh, could you please send me a video on WhatsApp?
